### ISSUE TITLE
Appreciation & A Couple of Data Issues

### ISSUE THREAD

**Issue by JohnSparks2024** [fja05680/sp500#15]
Hi,

Also want to express my gratitude for your efforts and maintaining this list of S&P 500 members.

I am collecting material to teach a college course in stock data and trading and this will be an excellent resource.

Having said that....

I noticed that you have two records for June 21, 2022.  I simply changed the date for the second one to a day later. Let me know if you think that is the best prescription or if one of the records should simply be deleted.

Second, I noticed that FTCP is present only on the record for November 10 of 2015.  I realize this is part of the historical data you got from the Trading Evolved book support site, so I did a little digging.  On this post (https://press.spglobal.com/2015-11-02-Four-Corners-Property-Trust-Set-to-Join-the-S-P-SmallCap-600) it is stated that FTCP was placed on the S&P 500 for one day on a zero price basis in order to account for some spin-off or something.  Based on this I will remove FTCP from the data.  I suggest you do the same.

Best wishes,
--John Sparks

**Comment by fja05680** [comment]
John,
Thank you for kind words.  I'm a bit jealous.  I came close to getting a positions as a financial analyst once, but alas it wasn't to be.  Always thought it would be cool to get paid for my hobby.  I'm glad you are finding this little project useful.  For the first point you mention, they should be merged into June 21, 2022.  Though it doesn't really matter.  What you did is fine.  I'll correct that on my next update.  Nice catch, thanks!!

On the second point.  I'm not planning on modifying the original historical data.  It would just become a rabbit hole.  Others have also pointed out some inaccuracies.  What I would love to do it create a file with know corrections, then apply it to the original.  I just don't have the time anymore.  Good luck with your course!!  Farrell

**Comment by fja05680** [comment]
I merged the two records for June 21, 2022.
